# Generated by Django 3.1.2 on 2020-11-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('stock', models.IntegerField(max_length=50)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
    ]
