# Generated by Django 3.1.2 on 2020-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201122_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateField(),
        ),
    ]
