# Generated by Django 3.1.2 on 2020-11-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20201120_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
